/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMOCKED_H
#define _MOCKMOCKED_H

#include "unity.h"
#include "mocked.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockmocked_Init(void);
void Mockmocked_Destroy(void);
void Mockmocked_Verify(void);




#define gpio_read_Expect(gpio_num) TEST_FAIL_MESSAGE("gpio_read requires _ExpectAndReturn");
#define gpio_read_ExpectAndReturn(gpio_num, cmock_retval) gpio_read_CMockExpectAndReturn(__LINE__, gpio_num, cmock_retval)
void gpio_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int gpio_num, int cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
