/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "test_mock.h"

static const char* CMockString_gpio_num = "gpio_num";
static const char* CMockString_gpio_read = "gpio_read";

typedef struct _CMOCK_gpio_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_gpio_num;

} CMOCK_gpio_read_CALL_INSTANCE;

static struct MockmockedInstance
{
  CMOCK_MEM_INDEX_TYPE gpio_read_CallInstance;
} Mock;


void Mockmocked_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.gpio_read_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockmocked_Init(void)
{
  Mockmocked_Destroy();
}

void Mockmocked_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int gpio_read(int gpio_num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_read);
  cmock_call_instance = (CMOCK_gpio_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_read_CallInstance);
  Mock.gpio_read_CallInstance = CMock_Guts_MemNext(Mock.gpio_read_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_read,CMockString_gpio_num);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_gpio_num, gpio_num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_gpio_read(CMOCK_gpio_read_CALL_INSTANCE* cmock_call_instance, int gpio_num);
void CMockExpectParameters_gpio_read(CMOCK_gpio_read_CALL_INSTANCE* cmock_call_instance, int gpio_num)
{
  cmock_call_instance->Expected_gpio_num = gpio_num;
}

void gpio_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int gpio_num, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_read_CALL_INSTANCE));
  CMOCK_gpio_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_read_CallInstance = CMock_Guts_MemChain(Mock.gpio_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_read(cmock_call_instance, gpio_num);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

